### ISSUE TITLE
[功能请求] 将下载的条漫图片拼接成长图。

### ISSUE THREAD

**Issue by Geopanret** [BiliBili-Manga-Downloader-Dev-Team/BiliBili-Manga-Downloader#59]
### 原因

本人所看的条漫采用了此种分页方法，导致阅读不便。
希望能内置一个小功能，可以将条漫拼接成长图。
![image](https://github.com/BiliBili-Manga-Downloader-Dev-Team/BiliBili-Manga-Downloader/assets/88887974/21a24ded-c38a-417d-b26b-a13bd1a47eaf)

### 功能简述

在用户勾选该功能后，会将条漫的分图片按顺序拼接生成一个包含完整内容的长图。

### 功能逻辑

在用户勾选该功能后，会将条漫的分图片按顺序拼接生成一个包含完整内容的长图。

**Comment by Geopanret** [comment]
另外……想在此询问上传的cookie是否会被滥用。

**Comment by Zeal-L** [comment]
@Geopanret 
- 条漫的问题本作者也体验过，目前的解决方式是用pdf保存格式观看，或者试试专门看条漫的本地漫画浏览器。拼接图片不是没有想过，只是不好分别一部漫画是否属于条漫，以及拼接数量的标准是怎么决定的，都很模糊。

- cookie分两种
  1. 第一种是B站解析，这种的cookie只会在本地保存，在向官方请求的时候附加上，不会被滥用。
  2. 第二种是BiliPlus的cookie，这种据我所知，你得到的那一刻之前就已经把B站cookie托管给BiliPlus这个第三方了。这也是黑科技解锁章节的前提，我不能保证他们不会滥用。至少目前看起来是安全的，他们的社区也活跃很久了。如果你实在担心的话可以用个小号登入他们平台获取cookie

如果解决了你的疑问请回复一下(～￣▽￣)～ ~~(我好关闭这个问题)~~

**Comment by Geopanret** [comment]
okok，再次使用之后发现了pdf可以承担长图功能，但是也发现了一个bug，_那就是切换保存格式有概率不会立即响应在下次下载中_
总之先关闭吧，我另开一条写我发现的bug

**Comment by Zeal-L** [comment]
> okok，再次使用之后发现了pdf可以承担长图功能，但是也发现了一个bug，_那就是切换保存格式有概率不会立即响应在下次下载中_ 总之先关闭吧，我另开一条写我发现的bug

是这样的
![image](https://github.com/BiliBili-Manga-Downloader-Dev-Team/BiliBili-Manga-Downloader/assets/72005386/d3d7d0c9-e170-46f1-acf3-da4b9f62e310)
需要重新启动一次软件~
